name: bdc_website_v2
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.13.0
  vrouter: ^1.2.1
  rive: ^0.11.1
  get_storage: 
  url_launcher: ^6.1.10
  marquee: ^2.2.3
  firebase_analytics: ^10.2.1
  animated_text_kit: ^4.2.2
  font_awesome_flutter: ^10.4.0
  video_player: ^2.6.1
  image_picker_web: ^3.0.0+1
  cloud_firestore: ^4.8.1
  firebase_storage: ^11.2.3
  universal_io: ^2.2.2
  firebase_auth: ^4.6.3
  flutter_riverpod: ^2.3.6
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  loading_overlay: ^0.3.0
  logger: ^1.1.0
  lottie: null
  stacked: ^3.4.0
  stacked_services: ^1.0.0
  responsive_builder: ^0.7.0
  equatable: ^2.0.5
  firebase_ui_auth: ^1.4.3
  file_picker: ^5.3.2
  percent_indicator: ^4.2.3
  syncfusion_flutter_pdfviewer:
  carousel_slider: ^4.2.1
  custom_alert_dialog_box: ^1.0.2
  quill_html_editor:
  fast_cached_network_image: ^1.2.0
  quds_popup_menu: ^0.0.1+1
  flutter_ad_manager_web: ^0.0.1
  admanager_web: ^0.0.3
  line_icons: ^2.0.3
  json_dynamic_widget:
  flutter_colorpicker: ^1.0.3
  hexcolor: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/files/
  fonts:
    - family: Primetime
      fonts:
        - asset: assets/fonts/PRIMETIME.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica-Bold.ttf
          weight: 600
        - asset: assets/fonts/Helvetica-BoldOblique.ttf
          weight: 800
        - asset: assets/fonts/Helvetica-light-1.ttf
          weight: 100
        - asset: assets/fonts/Helvetica-Oblique.ttf
          weight: 500
        - asset: assets/fonts/Helvetica.ttf
          weight: 400

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
